# Generated by Django 6.0.2 on 2026-02-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_taskcompletion_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('comment', 'Comment'), ('subscribe', 'Subscribe')], default='normal', max_length=20),
        ),
    ]
