# Generated by Django 6.0.2 on 2026-02-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_payout_task_cost_per_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('comment', 'Comment'), ('subscribe', 'Subscribe')], default='follow', max_length=20),
        ),
    ]
