# Generated by Django 6.0.2 on 2026-06-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_requested_at_withdrawalrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompletion',
            name='approved',
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
