# Generated by Django 6.0.2 on 2026-06-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_notification_link_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
