# Generated by Django 6.0.2 on 2026-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_referral_referral_code_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('comment', 'Comment'), ('subscribe', 'Subscribe'), ('repost', 'Repost')], default='follow', max_length=20),
        ),
    ]
