# Generated by Django 6.0.2 on 2026-07-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingpayment',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fundingpayment',
            name='method',
            field=models.CharField(choices=[('card', 'Card / Apple Pay'), ('bank', 'Bank Transfer')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='fundingpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fundingpayment',
            name='total_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
