# Generated by Django 6.0.2 on 2026-07-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_fundingpayment_fee_fundingpayment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_verification', 'Awaiting Verification'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=40),
        ),
    ]
