# Generated by Django 6.0.2 on 2026-07-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_fundingpayment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_verification', 'Awaiting Verification'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
