# Generated by Django 6.0.2 on 2026-07-13 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_admincampaign_campaignsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_withdrawal_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
