# Generated by Django 6.0.2 on 2026-07-14 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_first_withdrawal_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Main newsletter message. Line breaks are preserved.')),
                ('audience', models.CharField(choices=[('all', 'All active users'), ('members', 'Members only'), ('non_members', 'Non-members only'), ('staff', 'Staff users only')], default='all', max_length=20)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('action_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', editable=False, max_length=20)),
                ('sent_count', models.PositiveIntegerField(default=0, editable=False)),
                ('failed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('skipped_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
