# Generated by Django 6.0.2 on 2026-08-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
