# Generated by Django 6.0.2 on 2026-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_withdrawalrequest_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingpayment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fundingpayment',
            name='currency_paid',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='fundingpayment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fundingpayment',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='fundingpayment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fundingpayment',
            name='method',
            field=models.CharField(choices=[('card', 'Card / Apple Pay'), ('bank', 'Bank Transfer'), ('nigeria', 'Nigeria / Flutterwave')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='fundingpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
